# Generated by Django 4.0.3 on 2023-03-05 07:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_list', '0006_alter_shoppinglist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 3, 5, 9, 56, 0, 856520)),
        ),
    ]
